#!/usr/bin/env python3
import requests
import sys

r = requests.post('http://localhost:48100/banSubstrings',
    json={
        "ContextId": sys.argv[1],
        "Substrings": sys.argv[2:],
    },
    timeout=10.0,
)
print(r.status_code)
print(r.text)
