#!/usr/bin/env python3
import json
import requests
import sys

while True:
    r = requests.post('http://localhost:48100/speak',
        json={
            "ContextId": sys.argv[1],
            "Input": input().strip(),
        },
        timeout=10.0,
    )
    result = r.json()
    if result:
        print(json.dumps(result[0], indent=4))
    else:
        print("I don't know enough to respond to you; please converse in my presence so I can learn more.")
        
