#!/usr/bin/env python3
import json
import requests
import sys

while True:
    r = requests.post('http://localhost:48100/speak',
        json={
            "ContextId": sys.argv[1],
            "Input": input().strip(),
        },
        timeout=10.0,
    )
    print(json.dumps(r.json(), indent=4))
    
