#!/usr/bin/env python3
import requests
import sys

training_data = [line.strip() for line in open(sys.argv[2])]

r = requests.post('http://localhost:48100/learn',
    json={
        "ContextId": sys.argv[1],
        "Input": [line for line in training_data if line],
    },
    timeout=10.0,
)
print(r.status_code)
print(r.text)
